title: "AppQuality Badge"
description: "Documentation about AppQuality Quality Badge Widget"
logo: "https://s3-eu-west-1.amazonaws.com/appq.static/aq-logo.svg"
show_downloads: false
theme: jekyll-theme-minimal
